language: python
python:
  - "2.7"
# command to install dependencies
install:
  - make install
  - make install-coverage
  - pip install coveralls --use-mirrors
# command to run tests
script: make clitest
after_success: coveralls
